# 工作流名称，不设置默认就取文件名
name: GLaDOS-checkin
# 指定触发workflow的条件，当指定触发事件时可以限定分支或标签。当前是PR时触发
on:
  push:
  pull_request:
  watch:
    types: [ started ]
  # 任务计划，周期性主动执行
  schedule:
    - cron: 9 1 * * *
# 工作流执行的任务
jobs:
  GLaDOS-checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2   # 将代码拷贝到虚机中
      - name: Set execute permissions
        run: chmod +x ./checkin.sh
      - name: checkin
        env:  
          COOKIE: ${{ secrets.COOKIE }}
          SCKEY: ${{ secrets.SCKEY }}
        run: ./checkin.sh

